title:              Automatiko Blog
email:              automatiko-dev@googlegroups.com
description:        A Blog about Automatiko project
author:             Automatiko team
baseurl:            "/"
url:                "https://blog.automatiko.io/"

# Social Profiles
twitter_username:   automatiko_io
github_username:    automatiko_io
facebook_username:
instagram_username:
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   G-26JXBQJS49 # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
